// This file is automatically generated by Firebase Studio.
// Do not edit this file manually.

// To change this configuration, please go to the Firebase console.
// https://console.firebase.google.com/

// Your web app's Firebase configuration
// For Firebase JS SDK v7.20.0 and later, measurementId is optional
export const firebaseConfig = {
  "apiKey": "REDACTED",
  "authDomain": "REDACTED",
  "projectId": "REDACTED",
  "storageBucket": "REDACTED",
  "messagingSenderId": "REDACTED",
  "appId": "REDACTED"
};
